#!/bin/bash
mkdir ~/.jarvis
cp -R * ~/.jarvis
cp res/jarvis.desktop ~/.local/share/applications/
echo "Exec=python "$HOME"/.jarvis/main.py">>~/.local/share/applications/jarvis.desktop
echo "Icon="$HOME"/.jarvis/res/jarvis.png">>~/.local/share/applications/jarvis.desktop
echo "If no error occured then installation successful!!"
